### ISSUE TITLE
Generate toString, equals and hashCode implementations

### ISSUE THREAD

**Issue by andriy-dmytruk** [micronaut-projects/micronaut-sourcegen#126]
### Feature description

We can generate implementations for these methods to simplify development. We should probably include superclasses.

Since we cannot generate methods in the original class, we could generate something like `[classname]Utils` similarly to the way we generate `[classname]Builder`. Then the original class would reference the generated utility methods instead of needing to implement them similarly to how `builder()` static method can return a new builder.

Swagger generator mustache templates can be used as a reference, although we probably cannot support all the features, like hiding password in `toString`: 
```java
@Override
    public String toString() { {{#format-2}}
        java.lang.StringBuilder sb = new java.lang.StringBuilder();
        sb.append("{{classname}} (");
        {{#allVars}}
        sb.append("{{^-first}}, {{/-first}}{{name}}=");
            {{^isByteArray}}
                {{#isFormatPassword}}
        sb.append({{#isFormatPassword}}"<redacted>"{{/isFormatPassword}});
                {{/isFormatPassword}}
                {{^isFormatPassword}}
        sb.append(String.valueOf({{getter}}()));
                {{/isFormatPassword}}
            {{/isByteArray}}
            {{#isByteArray}}
        sb.append(String.valueOf({{getter}}()) + ({{getter}}() != null ? " (byte[" + {{getter}}().length + "])" : ""));
            {{/isByteArray}}
        {{/allVars}}
        sb.append(")");
        return sb.toString();
        {{/format-2}}
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof {{classname}})) {
            return false;
        }

        {{classname}} other = ({{classname}}) o;
        return {{#vars}}{{^-first}}    {{/-first}}{{^isByteArray}}java.util.Objects.equals(this.{{name}}, other.{{name}}){{/isByteArray}}{{#isByteArray}}java.util.Arrays.equals(this.{{name}}, other.{{name}}){{/isByteArray}}{{^-last}} &&
        {{/-last}}{{/vars}}{{^parent}}{{/parent}}{{#parent}}{{#hasVars}} &&
            {{/hasVars}}super.equals(other){{/parent}}{{^parent}}{{^hasVars}}true{{/hasVars}}{{/parent}};
    }

    @Override
    public int hashCode() {
        final int PRIME = 59;
        int result = {{#discriminator}}{{^hasSubtypes}}{{#parent}}super.hashCode(){{/parent}}{{^parent}}1{{/parent}}{{/hasSubtypes}}{{#hasSubtypes}}1{{/hasSubtypes}}{{/discriminator}}{{^discriminator}}1{{/discriminator}};
        {{#vars}}
        result = (result * PRIME) + {{^isByteArray}}(this.{{name}} == null ? 43 : this.{{name}}.hashCode()){{/isByteArray}}{{#isByteArray}}java.util.Arrays.hashCode(this.{{name}}){{/isByteArray}};
        {{/vars}}
        return result;
    }
```

**Comment by graemerocher** [comment]
great idea

**Comment by andriy-dmytruk** [comment]
Adding some technical requirements:

**toString**:
* Added with `@ToString` annotation and generated in the `[type]Utils` class.
* Probably best to be the same as it would be for record, e.g. `Person[name=Alice, age=25]`
* Use Arrays.toString for arrays.

**equals**:
* Ddded with `@Equals` annotation.
* Use == for primitive types
* Use Arrays.equals for arrays

**hash code**:
* Added with `@HashCode` annotation.
* Similar to record or lombok implementation (e.g. in prime choice). The lombok implementation is [HandleEqualsAndHashCode](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/eclipse/handlers/HandleEqualsAndHashCode.java) and [HandlerUtil](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/core/handlers/HandlerUtil.java#L70) and is essentially a loop of `hashValue = hashValue * 59 + propertyHashValue` starting with `hashValue = 1`.
* Special cases for primitive types and arrays:
   * null: `43`
   * boolean: `ref ? 79 : 97`
   * long: `(int)(ref >>> 32 ^ ref)`
   * float: `Float.floatToIntBits(fieldName)`
   * double: `longToIntForHashCode(Double.doubleToLongBits(fieldName))`
   * object: `fieldName == null ? 43 : fieldName.hashCode()`
   * arrays: `Arrays.hashCode(array)`
   * multidimensional arrays like `int[][]`: `Arrays.deepHashCode(array)`

Tests for each of the functions.

Example:
For this example user-written object
```java
@ToString
public class Elephant {
   private String name;
   public String getName() {
      return name;
   }
   public String toString() {
     return ElephantUtils.toString(this);
   }
}
```
I think the methods should be generated in the following way:
```java
public final class ElephantUtils {

  public String toString(Elephant object) {
    StringBuilder builder = new StringBuilder();
    builder.add("name").add(object.getName());
    return builder.toString()
  }

}
```

Other optional features
* Support inheritence correctly. For toString this means printing all the properties. For others it could be calling a method from parent class.
* Have a `@Secret` or `@ExcludeToString` annotation to exclude something from toString.
